name: Deploy App
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 2221 # Если ты настраивал 2221, поменяй здесь
          script: |
            mkdir -p ~/projects/my-app
            cd ~/projects/my-app
            
            if [ -d .git ]; then
              echo "Updating repository..."
              # Используем токен для обновления в приватном репо
              git remote set-url origin https://${{ secrets.GH_TOKEN }}@://github.com
              git fetch --all
              git reset --hard origin/main
            else
              echo "Cloning private repository..."
              # Используем токен для клонирования
              git clone https://${{ secrets.GH_TOKEN }}@://github.com .
            fi
            
            ls -la
            
            echo "Starting Docker..."
            docker compose up -d --build
