name: Deploy App
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 2221 # Оставь свой порт (2221 или 2222)
          script: |
            # 1. Жестко задаем переменную со ссылкой прямо в начале скрипта
            REPO_URL="https://github.com"
            
            mkdir -p ~/projects/my-app
            cd ~/projects/my-app
            
            echo "Cleaning up..."
            rm -rf * .git
            
            echo "Executing: git clone $REPO_URL ."
            # 2. Используем переменную в кавычках
            git clone "$REPO_URL" .
            
            echo "Current directory: $(pwd)"
            echo "Files list:"
            ls -F
            
            if [ -f "docker-compose.yml" ]; then
              echo "Starting Docker Compose..."
              docker compose up -d --build
            else
              echo "CRITICAL: docker-compose.yml NOT FOUND!"
              # Выведем содержимое папки подробнее для диагностики
              ls -la
              exit 1
            fi

